import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Header from '@/components/header';
import ReactQueryProvider from '../utils/providers/ReactQueryProvider';
import './globals.css';
import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/a95ba240bf.js" ></script>

      </head>
      <body>
        <ReactQueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <Header />
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
